const houses = [
    {
      id: '1',
      title: 'ghorofa jipya',
      price:'$1500',
      bathroom:'3',
      bedroom:'2',
      size:'200m',
      location: 'Mlalakuwa surevy kwa msekwa',
      image: require('../assets/house1.jpg'),
      details: `This building is located in the mlalakuwa area close to mpakani and survey bus stops..`,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    },
    {
      id: '2',
      title: 'kwa Mzee Shoo',
      price:'$1800',
      bathroom:'5',
      bedroom:'6',
      size:'400m',
      location: 'Mlalakuwa survey close to Pius Msekwa',
      image: require('../assets/house2.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    },
    {
      id: '3',
      title: 'msewe Appartments',
      price:'$2200',
      bathroom:'2',
      bedroom:'3',
      size:'170m',
      location: 'Close to the UDSM main campus(10 min drive) ',
      image: require('../assets/house3.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    },
    {
      id: '4',
      title: 'mama saada',
      price:'$3000',
      bathroom:'2',
      bedroom:'1',
      size:'150m',
      location: 'Mpakani area close to the bust stop',
      image: require('../assets/house4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    }, 
    {
      id: '5',
      title: 'mabibo hostels',
      price:'$2200',
      bathroom:'2',
      bedroom:'3',
      size:'170m',
      location: 'Close to the UDSM main campus(10 min drive) ',
      image: require('../assets/house3.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    },
    {
      id: '6',
      title: 'mbezi beach appartments',
      price:'$1500',
      bathroom:'3',
      bedroom:'2',
      size:'200m',
      location: 'Mlalakuwa surevy kwa msekwa',
      image: require('../assets/house1.jpg'),
      details: `This building is located in the mlalakuwa area close to mpakani and survey bus stops..`,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    }
  ];
  
  export default houses;
  